### ISSUE TITLE
Sun Flower missing textue

### ISSUE THREAD

**Issue by ghost** [Hecco56/Biome-Tinted-Flowers#1]
![2023-12-02_03 04 19](https://github.com/Hecco56/Biome-Tinted-Flowers/assets/130255931/580ca75a-a4e9-4fe5-a5c2-c5d2490c8ba4)

**Comment by Jerhom3** [comment]
I think this is caused by placing a sunflower in a biome tagged with has_closer_water_fog in data/minecraft/tags/worldgen/biome since i was able to replicate the issue with my datapack that had, sunflower plains tagged as has_closer_water_fog
![image](https://github.com/Hecco56/Biome-Tinted-Flowers/assets/152254711/9523029f-204e-422d-af0a-35d41511f026)

I cant find anything in my logs either, but i know it also happens in swamp biomes on default
![image](https://github.com/Hecco56/Biome-Tinted-Flowers/assets/152254711/1c1d9238-9d5a-4813-bbb9-d5d4d5349260)
![image](https://github.com/Hecco56/Biome-Tinted-Flowers/assets/152254711/6e488dc7-e92e-492d-8308-c0a4cc7c4067)

**Comment by Hecco56** [comment]
Idk how I missed this 😅 
Anyways, I found the issue, the model was simply pointing to a model file that didn't exist. I'll release a hotfix now! :)
